export interface Project {
  id: string
  title: string
  role: string
  org: string
  year: string
  description: string
  bullets: string[]
  tech: string[]
  links: { label: string; url: string }[]
}

export const jobs: Project[] = [
  {
    id: 'enzygent',
    title: 'Enzygent',
    role: 'Infrastructure, Deployment & Interface Design · Research Institute of the McGill University Health Centre (RI-MUHC), Dr. Brian Chen Lab',
    org: 'enzygent.org',
    year: 'May 2026 – Present',
    description: '',
    bullets: [
      'An enzyme-discovery platform: give it a starting molecule and a target, and it finds enzymes that could bridge the two — from the literature where one is known, generated by protein-design models where none is.',
      'Moved it off a laptop process onto dedicated hardware — an Ubuntu machine that began in my apartment and now sits in the lab at Montreal General. Hospital networks refuse inbound connections, so rather than forwarding ports I routed the site out through a Cloudflare named tunnel: nothing listening, and the address held when the machine changed buildings and subnets. Three services under a restricted account, back up on their own after a power cut.',
      'Fixed three production failures at the cause instead of the symptom: a recurring "database is locked" traced to journalling mode rather than answered with a restart; an evidence layer quietly returning nothing because a one-time data import had never run on that machine; and molecules compared in the wrong charge state, so ordinary input matched nothing at all.',
      'Added a mass-balance check that discards any match whose enzyme class disagrees with the atoms gained or lost — removing a category of confident wrong answers, and leaving a tool that returns nothing rather than something misleading.',
      'Set the product\'s visual direction and built it into tokens and components — typographic and quiet rather than the usual card grid — then rebuilt the submission screen, results view, and internal tools on it. Moved the answer to the top of the results page, and gave every colour-coded tag a written label so nothing reads by colour alone.',
      'Built the interface for the generative side and its safety screening, with an approval step that needs a second researcher rather than an administrator — closer to how review actually works in a lab.',
      'Set up continuous integration and wrote the operations guide so the lab can run the server without me.',
    ],
    tech: ['Ubuntu', 'systemd', 'Cloudflare Tunnel', 'GitHub Actions', 'FastAPI', 'Python', 'Next.js', 'React', 'TypeScript', 'RDKit', 'SQLite', 'PostgreSQL', 'Mol*', 'RFdiffusion', 'ProteinMPNN'],
    links: [
      { label: 'Live', url: 'https://enzygent.org' },
    ],
  },
  {
    id: 'rimuhc',
    title: 'Web Developer Intern — Genedig',
    role: 'Research Institute of the McGill University Health Centre (RI-MUHC) · Dr. Brian Chen Lab',
    org: 'genedig.org',
    year: 'Jun 2025 – Sep 2025 · Jul 2026 – Mar 2027',
    description: '',
    bullets: [
      'Refactoring Genedig, the lab\'s published genome browser (BMC Bioinformatics, 2015) for co-navigating DNA, RNA, and protein sequences, under contract through March 2027.',
      'Diagnosed and fixed critical bugs across Genedig\'s PHP/JavaScript codebase, improving platform stability and reducing downtime for the research team.',
      'Built a local XAMPP/MySQL development environment that streamlined onboarding and let the team reproduce and troubleshoot issues faster.',
      'Demoed the working platform to the research group, walking through fixes and gathering feedback to prioritize next steps.',
    ],
    tech: ['PHP', 'JavaScript', 'Angular', 'MySQL', 'XAMPP'],
    links: [{ label: 'Site', url: 'https://genedig.org/home' }],
  },
]

export const projects: Project[] = [
  {
    id: 'springboard',
    title: 'Springboard.io',
    role: 'Co-creator · MDN Web Docs Hackathon',
    org: 'springboard-io.vercel.app',
    year: 'Mar 2026 – Apr 2026',
    description: '',
    bullets: [
      'Co-built an agentic employee-onboarding platform end-to-end in a single afternoon sprint — finalist, top 5 of 16 teams at the McGill Data Network Hackathon.',
      'Shipped a working product under extreme time pressure using Next.js 16 and the Vercel AI SDK (Gemini), prioritizing a demoable end-to-end flow over feature breadth.',
      'Designed agentic workflows that automated access provisioning and generated personalized intro emails for new hires.',
      'Architected a RAG pipeline so new hires could get context-aware answers from internal docs instead of hunting through wikis.',
    ],
    tech: ['Next.js', 'Vercel AI SDK', 'Gemini', 'RAG', 'TypeScript'],
    links: [
      { label: 'GitHub', url: 'https://github.com/SamLev-2004/Springboard.io' },
      { label: 'Live', url: 'https://springboard-io.vercel.app' },
    ],
  },
  {
    id: 'chipseq',
    title: 'DNA Sequence Binding Analysis',
    role: 'Bioinformatics · McGill University',
    org: 'github.com/GatlatJack',
    year: '2024 – 2025',
    description: '',
    bullets: [
      'Built a Python/Bash pipeline to process ChIP-seq data and call peaks, identifying transcription factor binding sites across the genome.',
      'Identified transcription-factor binding motifs from ChIP-seq peaks and characterized protein–DNA interaction patterns.',
      'Automated peak-calling and visualization end-to-end, cutting manual analysis steps out of the workflow.',
    ],
    tech: ['Python', 'Bash', 'Bioinformatics', 'ChIP-seq'],
    links: [{ label: 'GitHub', url: 'https://github.com/GatlatJack' }],
  },
  {
    id: 'diagnostic',
    title: 'Medical Diagnostic Support System',
    role: 'ML Developer · McGill University',
    org: 'github.com/GatlatJack',
    year: '2024 – 2025',
    description: '',
    bullets: [
      'Built a Python diagnostic tool that compares patient symptoms against a case database to surface candidate diagnoses.',
      'Implemented a K-Nearest Neighbours classifier for multi-class disease prediction, validating accuracy across held-out test cases.',
    ],
    tech: ['Python', 'scikit-learn', 'KNN', 'Pandas'],
    links: [{ label: 'GitHub', url: 'https://github.com/GatlatJack' }],
  },
]
